# This file was generated by GoReleaser. DO NOT EDIT.
cask "memory-bank" do
  desc "Semantic memory management system for Claude Code using hexagonal architecture"
  homepage "https://github.com/joern1811/memory-bank"
  version "1.12.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memory-bank"

  on_macos do
    on_intel do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.12.8/memory-bank_1.12.8_darwin_amd64.tar.gz"
      sha256 "165b1bfeff8ef48ec037a075851b5b26af70809238bc4aead993edad7cfbd66b"
    end
    on_arm do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.12.8/memory-bank_1.12.8_darwin_arm64.tar.gz"
      sha256 "70fb0738b67798523431ee6a625ca4205a72a8eb76883aca3d3402f596a3bb98"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.12.8/memory-bank_1.12.8_linux_amd64.tar.gz"
      sha256 "a00896ae16b73e0389f0fe3ed0e2a17f0fe30b868d5fe5ce3ccafda69f95cbec"
    end
    on_arm do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.12.8/memory-bank_1.12.8_linux_arm64.tar.gz"
      sha256 "22a475a405b70b1e25ce61f6c8f133a94b1949ed5085207c346d617c90a5e47e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memory-bank"]
    system "#{staged_path}/memory-bank completion bash > #{HOMEBREW_PREFIX}/etc/bash_completion.d/memory-bank"
    system "#{staged_path}/memory-bank completion zsh > #{HOMEBREW_PREFIX}/share/zsh/site-functions/_memory-bank"
    system "#{staged_path}/memory-bank completion fish > #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/memory-bank.fish"
  end

  caveats do
    "Memory Bank works out-of-the-box with mock providers, but for enhanced performance, "
    "consider installing these optional services:"
    ""
    "For local embedding generation:"
    "  brew install ollama"
    "  ollama pull nomic-embed-text"
    ""
    "For vector search performance:"
    "  # Option 1: Python package"
    "  pip install chromadb"
    ""
    "  # Option 2: uvx (no installation needed)"
    "  uvx --from 'chromadb[server]' chroma run --host localhost --port 8000"
    ""
    "  # Option 3: Docker"
    "  docker run -p 8000:8000 chromadb/chroma"
    ""
    "Start Memory Bank MCP server:"
    "  memory-bank"
  end

  # No zap stanza required
end
