# This file was generated by GoReleaser. DO NOT EDIT.
cask "memory-bank" do
  desc "Semantic memory management system for Claude Code using hexagonal architecture"
  homepage "https://github.com/joern1811/memory-bank"
  version "1.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memory-bank"

  on_macos do
    on_intel do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.13.0/memory-bank_1.13.0_darwin_amd64.tar.gz"
      sha256 "f5890eac4155df9dded358f7f80586ac45111b845138ac1658dc346e668cbc2e"
    end
    on_arm do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.13.0/memory-bank_1.13.0_darwin_arm64.tar.gz"
      sha256 "4d290e82a1ab17a926c1f4015dac561850286889ee317d6b59f5ea3fa15d3a15"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.13.0/memory-bank_1.13.0_linux_amd64.tar.gz"
      sha256 "73c70dae69594036e1dbe083faf90ad9b8380704d424ce12e630a9b671f191dd"
    end
    on_arm do
      url "https://github.com/joern1811/memory-bank/releases/download/v1.13.0/memory-bank_1.13.0_linux_arm64.tar.gz"
      sha256 "182673334c1f8376efca2256210edc685e2f6ab624072b849eea00afde2fd952"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memory-bank"]
    system "#{staged_path}/memory-bank completion bash > #{HOMEBREW_PREFIX}/etc/bash_completion.d/memory-bank"
    system "#{staged_path}/memory-bank completion zsh > #{HOMEBREW_PREFIX}/share/zsh/site-functions/_memory-bank"
    system "#{staged_path}/memory-bank completion fish > #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/memory-bank.fish"
  end

  caveats do
    "Memory Bank works out-of-the-box with mock providers, but for enhanced performance, "
    "consider installing these optional services:"
    ""
    "For local embedding generation:"
    "  brew install ollama"
    "  ollama pull nomic-embed-text"
    ""
    "For vector search performance:"
    "  # Option 1: Python package"
    "  pip install chromadb"
    ""
    "  # Option 2: uvx (no installation needed)"
    "  uvx --from 'chromadb[server]' chroma run --host localhost --port 8000"
    ""
    "  # Option 3: Docker"
    "  docker run -p 8000:8000 chromadb/chroma"
    ""
    "Start Memory Bank MCP server:"
    "  memory-bank"
  end

  # No zap stanza required
end
