# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc ""
  homepage "https://github.com/joern1811/ai"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/joern1811/ai/releases/download/v0.4.2/ai_Darwin_x86_64.tar.gz"
      sha256 "af859e6163acd602773248b5b436767eac8a6df5e782e772ceadf9f0ff110595"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
    on_arm do
      url "https://github.com/joern1811/ai/releases/download/v0.4.2/ai_Darwin_arm64.tar.gz"
      sha256 "4d187dfa776d35e1d8bd7aa5cb04e6b8d91e9c3cfc30f78b42cc1f80f3a409b6"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joern1811/ai/releases/download/v0.4.2/ai_Linux_x86_64.tar.gz"
        sha256 "d62502ee853a994332f90deebde29a2aa12303135ef58f5d9288e461bb515d55"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai.bash" => "ai"
          zsh_completion.install "completions/ai.zsh" => "_ai"
          fish_completion.install "completions/ai.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joern1811/ai/releases/download/v0.4.2/ai_Linux_arm64.tar.gz"
        sha256 "d49feb5ff8f9bd28942327064f76c6b56613db35dce88913d01448fbcb8edca0"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai.bash" => "ai"
          zsh_completion.install "completions/ai.zsh" => "_ai"
          fish_completion.install "completions/ai.fish"
        end
      end
    end
  end
end
