# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc ""
  homepage "https://github.com/joern1811/ai"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/joern1811/ai/releases/download/v0.3.0/ai_Darwin_x86_64.tar.gz"
      sha256 "af5ae89210c2eb18c37850446b8f61e6e55dd1a05658579562104e2fd479aa84"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
    on_arm do
      url "https://github.com/joern1811/ai/releases/download/v0.3.0/ai_Darwin_arm64.tar.gz"
      sha256 "8b8c924e43e2fabdc2804230621e32e46bf6f6ebff2188cb3b5ec7fbf144e5bf"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joern1811/ai/releases/download/v0.3.0/ai_Linux_x86_64.tar.gz"
        sha256 "2297e3605b00d915242edccb542d3f88d1e455e8df97b8b4c5548a327785a137"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai.bash" => "ai"
          zsh_completion.install "completions/ai.zsh" => "_ai"
          fish_completion.install "completions/ai.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joern1811/ai/releases/download/v0.3.0/ai_Linux_arm64.tar.gz"
        sha256 "63950af6f35b60027195c89ddda23d91b64fc81a02a63f0762e90c0f3c1fe599"

        def install
          bin.install "ai"
          bash_completion.install "completions/ai.bash" => "ai"
          zsh_completion.install "completions/ai.zsh" => "_ai"
          fish_completion.install "completions/ai.fish"
        end
      end
    end
  end
end
