# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc ""
  homepage "https://github.com/joern1811/ai"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/ai/releases/download/v0.1.1/ai_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1e1fa6b8e96c4db0ee0ef0515f5ea23e0b45575fb1cfa949b6fa1ff7a84cbfba"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joern1811/ai/releases/download/v0.1.1/ai_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "970600136ddda20c3239c127a3709cd63d4a861e60879819c839e01e29b622cc"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/ai/releases/download/v0.1.1/ai_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b9b5f3718e5f276977a4eaef2be5c0419187b021abb13352d15bb15b74856823"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/ai/releases/download/v0.1.1/ai_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3b7a8e5975300688e376c910eee10492f91fe17370364b7571e18f608493ea36"

      def install
        bin.install "ai"
        bash_completion.install "completions/ai.bash" => "ai"
        zsh_completion.install "completions/ai.zsh" => "_ai"
        fish_completion.install "completions/ai.fish"
      end
    end
  end
end
