# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class McpAuthProxy < Formula
  desc "Local MCP auth proxy that injects authentication for upstream API targets"
  homepage "https://github.com/joern1811/mcp-auth-proxy"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/mcp-auth-proxy/releases/download/v1.1.0/mcp-auth-proxy_1.1.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3967dabbc30b50d0939851a67e560e64537afcab2c1a355dfa313ee7369cabf5"

      def install
        bin.install "mcp-auth-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joern1811/mcp-auth-proxy/releases/download/v1.1.0/mcp-auth-proxy_1.1.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "28408e5d3655a067cf9cb89e58c7af057016bb96043ae230509ff127d50f12d6"

      def install
        bin.install "mcp-auth-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/mcp-auth-proxy/releases/download/v1.1.0/mcp-auth-proxy_1.1.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6f0e6d36cd4cacab60f02e9cac1859b7bfbbfa8f889e390a5d651d7032d0d77d"
      def install
        bin.install "mcp-auth-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/mcp-auth-proxy/releases/download/v1.1.0/mcp-auth-proxy_1.1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "df72d18a436ecee1778ebe7dd90c011b7748b8e26bc4142dedd6038b7e77f790"
      def install
        bin.install "mcp-auth-proxy"
      end
    end
  end

  test do
    system "#{bin}/mcp-auth-proxy", "--version"
  end
end
