# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemoryBank < Formula
  desc "Semantic memory management system for Claude Code using hexagonal architecture"
  homepage "https://github.com/joern1811/memory-bank"
  version "1.11.0"
  license "MIT"

  depends_on "chromadb" => :optional
  depends_on "ollama" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/memory-bank/releases/download/v1.11.0/memory-bank_1.11.0_darwin_amd64.tar.gz"
      sha256 "64dec42f62cf079645e43530e1e58af2fbfae715fa85c8678270ee01f5b885f9"

      def install
        bin.install "memory-bank"
        generate_completions_from_executable(bin/"memory-bank", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joern1811/memory-bank/releases/download/v1.11.0/memory-bank_1.11.0_darwin_arm64.tar.gz"
      sha256 "d6ad252411d4bccadc5d928b209556b79b565d9feca1eef12a1c6e5408051139"

      def install
        bin.install "memory-bank"
        generate_completions_from_executable(bin/"memory-bank", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/memory-bank/releases/download/v1.11.0/memory-bank_1.11.0_linux_amd64.tar.gz"
      sha256 "3bfe1e922c7a82517997861d50ca98fc01194ae0f31e13f2f872153bc1682bb6"
      def install
        bin.install "memory-bank"
        generate_completions_from_executable(bin/"memory-bank", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/memory-bank/releases/download/v1.11.0/memory-bank_1.11.0_linux_arm64.tar.gz"
      sha256 "fcf5288dfac73b72722ce17eef7615c86903b9daa9e7cbfbaed3b0a14186aed2"
      def install
        bin.install "memory-bank"
        generate_completions_from_executable(bin/"memory-bank", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/memory-bank", "--help"
  end
end
