# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Pme < Formula
  desc "pme — Personal Management Extensions CLI"
  homepage "https://github.com/joern1811/pme"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/pme/releases/download/v0.1.0/pme_0.1.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f199cddb0e0b66b4ee5ede4f033c3dbfa095e3024b1d542d6eab94a0266402ac"

      define_method(:install) do
        bin.install "pme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joern1811/pme/releases/download/v0.1.0/pme_0.1.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9530cd26ad632758a013c574e8692bb10bb514fd3de4479a7ebbe01025a7320a"

      define_method(:install) do
        bin.install "pme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/pme/releases/download/v0.1.0/pme_0.1.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "37abc87590144cf0a2efc429b93fdf4ef8e44d5e8f3c7d264ddedac469fc9f69"
      define_method(:install) do
        bin.install "pme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/pme/releases/download/v0.1.0/pme_0.1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0556741beb3a9ee7d953acfad67f2365b9697818edc4f6fde3937f9289426730"
      define_method(:install) do
        bin.install "pme"
      end
    end
  end

  test do
    system "#{bin}/pme", "--version"
  end
end
