# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Pme < Formula
  desc "pme — Personal Management Extensions CLI"
  homepage "https://github.com/joern1811/pme"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/pme/releases/download/v0.3.0/pme_0.3.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6569bce070e5074e9c5e7e477a7a13036460e74baeb5880eb18ab3abe208541f"

      define_method(:install) do
        bin.install "pme"
        bash_output = Utils.safe_popen_read(bin/"pme", "completion", "bash")
        (bash_completion/"pme").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"pme", "completion", "zsh")
        (zsh_completion/"_pme").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"pme", "completion", "fish")
        (fish_completion/"pme.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joern1811/pme/releases/download/v0.3.0/pme_0.3.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8494cf1539b3b6fadd67790b6c74f6a764e541bd5b0ca681fad628e08f3e4647"

      define_method(:install) do
        bin.install "pme"
        bash_output = Utils.safe_popen_read(bin/"pme", "completion", "bash")
        (bash_completion/"pme").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"pme", "completion", "zsh")
        (zsh_completion/"_pme").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"pme", "completion", "fish")
        (fish_completion/"pme.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/pme/releases/download/v0.3.0/pme_0.3.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1d1719a927da25290a8c8a8de918d57b2795efc29ba8f5f5bbfdd9074774772f"
      define_method(:install) do
        bin.install "pme"
        bash_output = Utils.safe_popen_read(bin/"pme", "completion", "bash")
        (bash_completion/"pme").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"pme", "completion", "zsh")
        (zsh_completion/"_pme").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"pme", "completion", "fish")
        (fish_completion/"pme.fish").write fish_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/pme/releases/download/v0.3.0/pme_0.3.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "505d7ed9079b19242d41f5580fb4d3f07916039c9e2214fbf96849b6d6a5b486"
      define_method(:install) do
        bin.install "pme"
        bash_output = Utils.safe_popen_read(bin/"pme", "completion", "bash")
        (bash_completion/"pme").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"pme", "completion", "zsh")
        (zsh_completion/"_pme").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"pme", "completion", "fish")
        (fish_completion/"pme.fish").write fish_output
      end
    end
  end

  test do
    system "#{bin}/pme", "--version"
  end
end
