# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wachat < Formula
  desc "Convert WhatsApp chat exports to readable text with voice message transcription."
  homepage "https://github.com/joern1811/wachat"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/wachat/releases/download/v1.0.0/wachat_Darwin_x86_64.tar.gz"
      sha256 "ce61cc172aa15e7239a496060f8b5ab6a9958d7010817fb5bfaf8ea7068871bc"

      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joern1811/wachat/releases/download/v1.0.0/wachat_Darwin_arm64.tar.gz"
      sha256 "0bc747968b6d7c11401ed1eac1f412ab73b197a181c5fe1ff13d757ec0d05e38"

      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/wachat/releases/download/v1.0.0/wachat_Linux_x86_64.tar.gz"
      sha256 "30e89e5d931024e45fa5aaf179b28eb4b56be22e7c146e0dfa6ed2f10d6ef3b2"
      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/wachat/releases/download/v1.0.0/wachat_Linux_arm64.tar.gz"
      sha256 "6f9f0dfc6e08e3d271ff71cd6f75e734346a96b264c3c8e3e366ad1c1e9e760f"
      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
  end
end
