# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wachat < Formula
  desc "Convert WhatsApp chat exports to readable text with voice message transcription."
  homepage "https://github.com/joern1811/wachat"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joern1811/wachat/releases/download/v1.1.1/wachat_Darwin_x86_64.tar.gz"
      sha256 "af90f48bcbd48ee6198444446c53036d5264210048bd48b607286797e630ddc1"

      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joern1811/wachat/releases/download/v1.1.1/wachat_Darwin_arm64.tar.gz"
      sha256 "bb744be0acc9c2333863d7ced745735c13e2ed98f8d35d4b1fe2ac08f7437d00"

      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/wachat/releases/download/v1.1.1/wachat_Linux_x86_64.tar.gz"
      sha256 "114c968f3ceae0415c827aeb25d17d849e2be7931dd1c281387ef8c8d838ea42"
      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joern1811/wachat/releases/download/v1.1.1/wachat_Linux_arm64.tar.gz"
      sha256 "4153d529bd3e9a7123fa383c2dad97208e393514ba63d6cd617b8349efbe92ee"
      define_method(:install) do
        bin.install "wachat"
        bash_completion.install "completions/wachat.bash" => "wachat"
        zsh_completion.install "completions/wachat.zsh" => "_wachat"
        fish_completion.install "completions/wachat.fish"
      end
    end
  end
end
